services:
  app:
    build:
      context: ./docker/php
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: app
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    networks:
      - laravel

  web:
    image: nginx:stable-alpine
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:16-alpine
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
